name: validate
on:
  push:
    branches: [ "main" ]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Basic check
        run: test -f index.html && echo "OK"
